### ISSUE TITLE
RFC-4122 specifies using lowercase

### ISSUE THREAD

**Issue by kanef** [danakt/uuid-by-string#1]
I'd like to point out that according to the [spec](https://tools.ietf.org/html/rfc4122#section-3),
>  The hexadecimal values “a” through “f” are output as  lower case characters and are case insensitive on input.

So this tool is technically not quite compliant, although I don't know how much practical consequence that is since tools that read the id are required to ignore the case.

It's probably a one-line change [here](https://github.com/danakt/uuid-by-string/blob/be4c6447963063d7090bcec02512af693707b7e1/src/index.js#L137), but of course the documentation and tests would also need to change to match.

**Comment by danakt** [comment]
Thanks for your comment @kanef. I can't fix this in the current version, as this can lead to unknown consequences in projects where the package is used. I think that in the near future I'll make these changes in next major version
