### ISSUE TITLE
Isn't generating same UUID for a given string always

### ISSUE THREAD

**Issue by Arsasana** [danakt/uuid-by-string#15]
Code snippet:
import generateUuid from "uuid-by-string";

convertStringToUUID (stringToConvert: string) {
    const uuidHash = generateUuid(stringToConvert);
    return uuidHash;
}

**Comment by Arsasana** [comment]
Working fine after adding a namespace

**Comment by danakt** [comment]
@Arsasana in the previous version, there was a bug of processing some utf-8 characters because of this, the function could return the same uuid for different inputs. The problem has been fixed in version 4.0
