### ISSUE TITLE
Module not es5 compatible

### ISSUE THREAD

**Issue by drogerie21** [danakt/uuid-by-string#2]
Hi, 

please provide your package es5 compatible. For example the index.js files uses object destructuring, an es6 feature:
`const { md5Hash, stringToCharBuffer, sha1Hash, hashToUuid, concatBuffers } = require('./lib')`

Best regards, Florian

**Comment by danakt** [comment]
Oops, thank you! Fixed in [2.1.0](https://github.com/danakt/uuid-by-string/commit/d3b788b163b1f66e375d76db8c6a3e6364c4c9b1)
