### ISSUE TITLE
Can't find variable: Buffer

### ISSUE THREAD

**Issue by mazenchami** [danakt/uuid-by-string#3]
Hi,

I found an issue with the following versions:
React: "16.8.3"
React-Native: "0.59.2"
uuid-by-string: "^2.1.0"

**Issue:**
in `/src/lib.js`, line 74, `...new Buffer...` returns the error. adding `import { Buffer, } from 'buffer';` to the top of the file and as a dependency in the `package.json` file, will solve this issue.

Please let me know if this can be fixed in the next version or if I need to handle it on my own?

Thanks,
-Mazen

**Comment by danakt** [comment]
Thank you! My bad. Fixed in 2.1.1
